package com.gameAd.maker.util;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by dell on 2017/3/17.
 */
public class BaseEntity implements Serializable{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.create_user
     *
     * @mbggenerated Fri Mar 17 14:10:29 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.create_time
     *
     * @mbggenerated Fri Mar 17 14:10:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.update_user
     *
     * @mbggenerated Fri Mar 17 14:10:29 CST 2017
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user.update_time
     *
     * @mbggenerated Fri Mar 17 14:10:29 CST 2017
     */
    private Date updateTime;

    private String isDel;

    public BaseEntity(){}

    public BaseEntity(boolean init) {
        if (init) {
            Date date = new Date();
            this.setCreateUser("admin");
            this.setCreateTime(date);
            this.setUpdateUser("admin");
            this.setUpdateTime(date);
            this.setIsDel("N");
        }
    }

    public String getIsDel() {
        return isDel;
    }

    public void setIsDel(String isDel) {
        this.isDel = isDel;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
